# Generated by Django 5.2.14 on 2026-06-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tanggal', models.DateField(verbose_name='Tanggal Terbit')),
                ('author', models.CharField(default='Admin BPH', max_length=100)),
                ('short', models.TextField(help_text='Ringkasan pendek artikel')),
                ('deskripsi', models.TextField(verbose_name='Konten Artikel Lengkap')),
                ('gambar', models.ImageField(upload_to='articles/', verbose_name='Foto Utama Artikel')),
            ],
            options={
                'verbose_name_plural': 'Artikel & Wawasan Teknis',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Instansi/Perusahaan')),
                ('alamat', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, help_text='Logo grup untuk bagian partner ticker', upload_to='clients/logos/')),
            ],
            options={
                'verbose_name_plural': 'Klien / Mitra Kolaborasi',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provinsi', models.CharField(max_length=150, verbose_name='Nama Provinsi')),
            ],
            options={
                'verbose_name_plural': 'Lokasi Wilayah',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nama Layanan')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('portfolio', models.CharField(choices=[('NRM', 'Natural Resources Management (NRM)'), ('NRU', 'Natural Resources Understanding (NRU)')], default='NRM', max_length=3)),
                ('bg_image', models.ImageField(blank=True, upload_to='services/banners/', verbose_name='Foto Banner Atas')),
                ('intro', models.TextField(verbose_name='Paragraf Ringkasan Atas')),
                ('approach', models.TextField(verbose_name='Paragraf Pendekatan Komprehensif')),
                ('categories', models.ManyToManyField(blank=True, related_name='services', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Layanan (Services)',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nama Proyek')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tahun', models.IntegerField(verbose_name='Tahun Pelaksanaan')),
                ('image', models.ImageField(upload_to='projects/thumbs/', verbose_name='Foto Kartu Proyek')),
                ('description', models.TextField(verbose_name='Deskripsi Project')),
                ('categories', models.ManyToManyField(related_name='projects', to='core.category', verbose_name='Kategori Proyek')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.location')),
                ('service_portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.service', verbose_name='Sesuai Portofolio Layanan')),
            ],
            options={
                'verbose_name_plural': 'Proyek (Experience)',
            },
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Nama icon Material Symbols, misal: 'forest', 'ecg', 'map'", max_length=50, verbose_name='Nama Icon')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Tahapan')),
                ('desc', models.TextField(verbose_name='Deskripsi Detail Tahapan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.service', verbose_name='Untuk Layanan')),
            ],
            options={
                'verbose_name_plural': 'Tahapan Pelaksanaan Layanan',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tanggal', models.DateField(verbose_name='Tanggal Rilis')),
                ('author', models.CharField(default='Admin BPH', max_length=100)),
                ('short', models.TextField(help_text='Ringkasan pendek yang muncul di kartu depan')),
                ('deskripsi', models.TextField(verbose_name='Isi Cerita Lengkap')),
                ('gambar', models.ImageField(upload_to='stories/', verbose_name='Foto Cerita')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'Cerita Lapangan',
            },
        ),
    ]
