# Generated by Django 5.2.14 on 2026-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email')),
                ('subjek', models.CharField(max_length=200, verbose_name='Subjek / Nama Instansi')),
                ('pesan', models.TextField(verbose_name='Detail Pesan / Pertanyaan')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Kirim')),
            ],
            options={
                'verbose_name_plural': 'Pesan Masuk Kontak',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Dokumen Publikasi')),
                ('file_dokumen', models.FileField(upload_to='documents/', verbose_name='Berkas File (PDF/Docs)')),
                ('tanggal_rilis', models.DateField(auto_now_add=True, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Dokumen Strategis',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
