# Generated by Django 5.2.14 on 2026-06-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_document_location_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Modul',
        ),
        migrations.AlterModelOptions(
            name='modul',
            options={'verbose_name_plural': 'Modul Dokumentasi'},
        ),
    ]
