# Generated by Django 5.2.14 on 2026-06-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_document_modul_alter_modul_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250, verbose_name='Keterangan Foto / Caption')),
                ('gambar', models.ImageField(upload_to='gallery/', verbose_name='File Foto')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='core.category', verbose_name='Kategori Filter')),
            ],
            options={
                'verbose_name_plural': 'Galeri Dokumentasi',
            },
        ),
    ]
