# Generated by Django 5.2.14 on 2026-07-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, verbose_name='Tantangan & Kondisi Awal'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Paragraf Pembuka Detail'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.TextField(blank=True, verbose_name='Pendekatan & Metodologi Kerja'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_cover',
            field=models.ImageField(blank=True, null=True, upload_to='projects/pdf_covers/', verbose_name='Sampul Modul PDF'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/pdf_files/', verbose_name='Berkas Modul Laporan Teknis (PDF)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, verbose_name='Hasil & Dampak Ekologis Terukur'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Nama icon Material Symbols, misal: 'forest', 'travel_explore'", max_length=50, verbose_name='Nama Icon Kartu'),
        ),
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='services/thumbs/', verbose_name='Foto Kartu Layanan'),
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200, verbose_name='Parameter Monitoring')),
                ('target', models.CharField(max_length=200, verbose_name='Target Awal')),
                ('actual', models.CharField(max_length=200, verbose_name='Realisasi Akhir Lapangan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.project', verbose_name='Untuk Proyek')),
            ],
            options={
                'verbose_name_plural': 'Matriks Capaian Kinerja Proyek',
            },
        ),
    ]
