# Generated by Django 5.2.14 on 2026-07-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lokasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.location', verbose_name='Lokasi Wilayah'),
        ),
    ]
