# Generated by Django 5.2.14 on 2026-07-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tanggal_upload',
            field=models.DateField(verbose_name='Tanggal Dokumentasi'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Folder / Album')),
                ('tahun', models.IntegerField(verbose_name='Tahun Dokumentasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='core.category', verbose_name='Kategori Filter')),
            ],
            options={
                'verbose_name_plural': 'Folder / Album Galeri',
                'ordering': ['-tahun', '-id'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.folder', verbose_name='Dimasukkan ke Folder'),
        ),
    ]
