# Generated by Django 5.2.14 on 2026-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gallery_tanggal_upload_folder_gallery_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(related_name='projects', to='core.location', verbose_name='Lokasi Wilayah Provinsi'),
        ),
    ]
