# Generated by Django 5.2.14 on 2026-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Lengkap & Gelar')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan / Posisi')),
                ('kategori', models.CharField(choices=[('advisors', 'Advisors'), ('executives', 'Executives'), ('staff', 'Staff'), ('associates', 'Associates')], default='advisors', max_length=20, verbose_name='Kategori Tim')),
                ('foto', models.ImageField(upload_to='team/', verbose_name='Foto Profil Anggota')),
                ('urutan', models.IntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu (0, 1, 2...)', verbose_name='Urutan Tampil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tim Ahli Kami',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
