# Generated by Django 5.2.14 on 2026-07-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Opsional. Boleh dikosongkan.', null=True, verbose_name='Bio / Cerita Singkat'),
        ),
    ]
