# Generated by Django 5.2.14 on 2026-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teammember_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sektor',
            field=models.CharField(choices=[('swasta', 'Sektor Swasta'), ('publik', 'Sektor Publik')], default='swasta', max_length=10, verbose_name='Kategori Sektor'),
        ),
    ]
