# Generated by Django 5.2.14 on 2026-07-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client_sektor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
