# Generated by Django 5.2.14 on 2026-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_client_alamat_remove_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='intro',
        ),
        migrations.AlterField(
            model_name='service',
            name='approach',
            field=models.TextField(verbose_name='Detail Deskripsi Cakupan Kerja'),
        ),
    ]
