# Generated by Django 5.2.14 on 2026-07-24 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_service_intro_alter_service_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometri Poligon Peta'),
        ),
    ]
