# Generated by Django 5.2.14 on 2026-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_location_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deskripsi_en',
            field=models.TextField(null=True, verbose_name='Konten Artikel Lengkap'),
        ),
        migrations.AddField(
            model_name='article',
            name='deskripsi_ind',
            field=models.TextField(null=True, verbose_name='Konten Artikel Lengkap'),
        ),
        migrations.AddField(
            model_name='article',
            name='judul_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='judul_ind',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='short_en',
            field=models.TextField(help_text='Ringkasan pendek artikel', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='short_ind',
            field=models.TextField(help_text='Ringkasan pendek artikel', null=True),
        ),
        migrations.AddField(
            model_name='modul',
            name='judul_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul Dokumen Publikasi'),
        ),
        migrations.AddField(
            model_name='modul',
            name='judul_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul Dokumen Publikasi'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tantangan & Kondisi Awal'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Tantangan & Kondisi Awal'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Deskripsi Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ind',
            field=models.TextField(null=True, verbose_name='Deskripsi Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraf Pembuka Detail'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraf Pembuka Detail'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology_en',
            field=models.TextField(blank=True, null=True, verbose_name='Pendekatan & Metodologi Kerja'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Pendekatan & Metodologi Kerja'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Nama Proyek'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ind',
            field=models.CharField(max_length=250, null=True, verbose_name='Nama Proyek'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hasil & Dampak Ekologis Terukur'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Hasil & Dampak Ekologis Terukur'),
        ),
        migrations.AddField(
            model_name='service',
            name='approach_en',
            field=models.TextField(null=True, verbose_name='Detail Deskripsi Cakupan Kerja'),
        ),
        migrations.AddField(
            model_name='service',
            name='approach_ind',
            field=models.TextField(null=True, verbose_name='Detail Deskripsi Cakupan Kerja'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nama Layanan'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Nama Layanan'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Deskripsi Detail Tahapan'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='desc_ind',
            field=models.TextField(null=True, verbose_name='Deskripsi Detail Tahapan'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul Tahapan'),
        ),
        migrations.AddField(
            model_name='servicestep',
            name='title_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul Tahapan'),
        ),
        migrations.AddField(
            model_name='story',
            name='deskripsi_en',
            field=models.TextField(null=True, verbose_name='Isi Cerita Lengkap'),
        ),
        migrations.AddField(
            model_name='story',
            name='deskripsi_ind',
            field=models.TextField(null=True, verbose_name='Isi Cerita Lengkap'),
        ),
        migrations.AddField(
            model_name='story',
            name='judul_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='judul_ind',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='short_en',
            field=models.TextField(help_text='Ringkasan pendek yang muncul di kartu depan', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='short_ind',
            field=models.TextField(help_text='Ringkasan pendek yang muncul di kartu depan', null=True),
        ),
    ]
