# Generated by Django 5.2.14 on 2026-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_article_deskripsi_en_article_deskripsi_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
