# Generated by Django 5.2.14 on 2026-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_article_slug_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='judul',
            field=models.CharField(max_length=250, verbose_name='Judul Artikel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='judul_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Artikel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='judul_ind',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Artikel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug English'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='story',
            name='judul',
            field=models.CharField(max_length=250, verbose_name='Judul Cerita'),
        ),
        migrations.AlterField(
            model_name='story',
            name='judul_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Cerita'),
        ),
        migrations.AlterField(
            model_name='story',
            name='judul_ind',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Cerita'),
        ),
    ]
