# Generated by Django 5.2.14 on 2026-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_article_author_alter_article_judul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nama_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nama Instansi/Perusahaan'),
        ),
        migrations.AddField(
            model_name='client',
            name='nama_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Nama Instansi/Perusahaan'),
        ),
        migrations.AddField(
            model_name='folder',
            name='nama_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nama Folder / Album'),
        ),
        migrations.AddField(
            model_name='folder',
            name='nama_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Nama Folder / Album'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='caption_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Keterangan Foto / Caption'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='caption_ind',
            field=models.CharField(max_length=250, null=True, verbose_name='Keterangan Foto / Caption'),
        ),
        migrations.AddField(
            model_name='location',
            name='nama_provinsi_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nama Provinsi'),
        ),
        migrations.AddField(
            model_name='location',
            name='nama_provinsi_ind',
            field=models.CharField(max_length=150, null=True, verbose_name='Nama Provinsi'),
        ),
        migrations.AddField(
            model_name='location',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Opsional. Boleh dikosongkan.', null=True, verbose_name='Bio / Cerita Singkat'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ind',
            field=models.TextField(blank=True, help_text='Opsional. Boleh dikosongkan.', null=True, verbose_name='Bio / Cerita Singkat'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='jabatan_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Jabatan / Posisi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='jabatan_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Jabatan / Posisi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='kategori_en',
            field=models.CharField(choices=[('advisors', 'Advisors'), ('executives', 'Executives'), ('staff', 'Staff'), ('associates', 'Associates')], default='advisors', max_length=20, null=True, verbose_name='Kategori Tim'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='kategori_ind',
            field=models.CharField(choices=[('advisors', 'Advisors'), ('executives', 'Executives'), ('staff', 'Staff'), ('associates', 'Associates')], default='advisors', max_length=20, null=True, verbose_name='Kategori Tim'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
