# Generated by Django 5.2.14 on 2026-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_article_slug_ind_category_name_en_category_name_ind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nama Lengkap'),
        ),
    ]
