# Generated by Django 5.2.14 on 2026-08-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_profile_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contributor', 'Contributor')], default='admin', max_length=20, verbose_name='Role Pengguna'),
        ),
    ]
