# Generated by Django 5.2.14 on 2026-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infografis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Infografis')),
                ('gambar', models.ImageField(upload_to='infografis/', verbose_name='Berkas Gambar/Infografis')),
                ('tanggal_unggah', models.DateField(auto_now_add=True, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Infografis & Data Visual',
                'ordering': ['-tanggal_unggah', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Video Kegiatan')),
                ('url_video', models.URLField(verbose_name='Link Video (YouTube/Lainnya)')),
                ('tanggal_unggah', models.DateField(auto_now_add=True, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Video Dokumenter Kegiatan',
                'ordering': ['-tanggal_unggah', '-id'],
            },
        ),
    ]
