# Generated by Django 5.2.14 on 2026-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_infografis_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-tanggal_unggah', '-id'], 'verbose_name_plural': 'Galeri Video Kegiatan'},
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Tayangan'),
        ),
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Tayangan'),
        ),
    ]
