# Generated by Django 5.2.14 on 2026-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_video_options_article_views_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infografis',
            name='judul',
        ),
        migrations.AddField(
            model_name='infografis',
            name='deskripsi',
            field=models.TextField(default='', verbose_name='Deskripsi Infografis'),
        ),
    ]
