# Generated by Django 5.2.14 on 2026-09-05 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_infografis_judul_infografis_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Terbit'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tanggal_upload',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Dokumentasi'),
        ),
        migrations.AlterField(
            model_name='infografis',
            name='tanggal_unggah',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Unggah'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='tanggal_rilis',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Unggah'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Rilis'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tanggal_unggah',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Unggah'),
        ),
    ]
