# Generated by Django 5.2.14 on 2026-09-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_article_tanggal_alter_gallery_tanggal_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Thumbnail Khusus (Opsional, untuk selain YT)'),
        ),
    ]
