# Generated by Django 5.2.14 on 2026-10-09 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250, verbose_name='Judul Program')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Dibuat')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Penulis')),
                ('short', models.TextField(help_text='Ringkasan pendek program')),
                ('deskripsi', models.TextField(verbose_name='Konten Program Lengkap')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Tayangan')),
                ('gambar', models.ImageField(upload_to='programs/', verbose_name='Foto Utama Program')),
            ],
            options={
                'verbose_name_plural': 'Program',
            },
        ),
    ]
