# Generated by Django 5.2.14 on 2026-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='deskripsi_en',
            field=models.TextField(null=True, verbose_name='Konten Program Lengkap'),
        ),
        migrations.AddField(
            model_name='program',
            name='deskripsi_ind',
            field=models.TextField(null=True, verbose_name='Konten Program Lengkap'),
        ),
        migrations.AddField(
            model_name='program',
            name='judul_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='judul_ind',
            field=models.CharField(max_length=250, null=True, verbose_name='Judul Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_en',
            field=models.TextField(help_text='Ringkasan pendek program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='short_ind',
            field=models.TextField(help_text='Ringkasan pendek program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slug_ind',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
