"""
Django settings for bph_project project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gex9-d@0-b(8$h_d+o#ygfdlagtda09hv&d6t2-qt9l-m-@^wn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin', #---template admin jazzmin
    # 'admin_interface',  #----template admin interface
    # 'colorfield', #----template admin interface
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bph_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bph_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# KONFIGURASI TEMA JAZZMIN (DIEDIT DI SINI UNTUK HUBUNGKAN FONT/WARNA DARI PDF)
# ==============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "BPH Admin",
    "site_header": "Bhumi Pasa Hijau",
    "site_brand": "Bhumi Pasa Hijau",
    "copyright": "Bhumi Pasa Hijau",
    "welcome_sign": "Selamat Datang di Dashboard Bhumi Pasa Hijau",

    "usermenu_links": [{"name": "Bhumi Pasa Hijau", "url": "/", "new_window": True}],
    "show_sidebar": True,
    "topmenu_links": [{"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]}], # <-- Tambah ini bro
    
    # --------------------------------------------------------------------------
    # CARA CUSTOM: Daftarkan file CSS custom biar warna & font presisi 100% dari PDF.
    # Buat filenya nanti di: core/static/core/css/custom_admin.css
    # (Hapus/Komentari baris di bawah ini jika lu cuma pengen tes cara instan dulu)
    # --------------------------------------------------------------------------
    "custom_css": "core/css/custom_admin.css",
    "custom_js": "core/js/custom_admin.js",
    "icons": {
        "auth.user": "fas fa-user-cog",
        "auth.Group": "fas fa-users",
        "core.Category": "fas fa-tags",
        "core.Service": "fas fa-hand-holding-heart",
        "core.ServiceStep": "fas fa-list-ol",
        "core.Location": "fas fa-map-marker-alt",
        "core.Client": "fas fa-handshake",
        "core.Project": "fas fa-project-diagram",
        "core.Story": "fas fa-book-open",
        "core.Article": "fas fa-newspaper",
    },
    "order_with_respect_to": [
        "auth", 
        "core.Service", 
        "core.ServiceStep", 
        "core.Category", 
        "core.Location", 
        "core.Client", 
        "core.Project", 
        "core.Story", 
        "core.Article"
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-success navbar-dark", 
    "sidebar": "sidebar-dark-success",     
    
    # --------------------------------------------------------------------------
    # CARA INSTAN: Ganti "theme" di bawah ini pake nama Bootswatch buat tes rasa instan.
    # Pilihan rasa instan yang ijo atau mirip font PDF: "minty", "flatly", "lux", "simplex"
    # --------------------------------------------------------------------------
    "theme": "flatly",  # Pilihan rasa instan yang ijo atau mirip font PDF: "minty", "flatly", "lux", "simplex"
}